/**
 * @core/branches — branch identity, id scheme, and wire schemas shared by the
 * server, the admin client, and the collab engine. Barrel-gated: import ONLY
 * from `@core/branches` outside this folder.
 */
export {
  BRANCH_ID_PATTERN,
  BRANCH_NAME_MAX_LENGTH,
  MAIN_BRANCH_ID,
  SITE_SHELL_LOGICAL_ID,
  isMainBranch,
  isValidBranchId,
  logicalIdOf,
  physicalId,
  slugifyBranchName,
} from './ids'
export { canActOnBranch, canMergeBranches, type BranchActor } from './access'
export { jsonEquals, mergeJson, type JsonMergeResult } from './threeWayMerge'
export {
  BranchEnvelopeSchema,
  BranchListEnvelopeSchema,
  BranchPreviewLinkEnvelopeSchema,
  BranchPreviewSchema,
  BranchPreviewStateEnvelopeSchema,
  CreateBranchBodySchema,
  RenameBranchBodySchema,
  SiteBranchSchema,
  ApplyMergeBodySchema,
  ApplyMergeEnvelopeSchema,
  BranchMergeRecordSchema,
  UndoMergeEnvelopeSchema,
  MergeChangeSchema,
  MergeChangeDetailSchema,
  MergeEntityKindSchema,
  MergeFieldChangeSchema,
  MergeTreeDiffSchema,
  MergeSchemaFieldSchema,
  BranchMergeRequestSchema,
  BranchReviewCommentSchema,
  BranchReviewStateSchema,
  CreateMergeRequestBodySchema,
  CreateReviewCommentBodySchema,
  DeclineMergeRequestBodySchema,
  MergeRequestEnvelopeSchema,
  MergeRequestStatusSchema,
  ReviewCommentEnvelopeSchema,
  ReviewRenderSideSchema,
  ReviewUserLabelSchema,
  REVIEW_COMMENT_MAX_LENGTH,
  REVIEW_NOTE_MAX_LENGTH,
  MergeDirectionSchema,
  MergePlanEnvelopeSchema,
  MergePlanSchema,
  MergeResolutionSchema,
  type ApplyMergeBody,
  type ApplyMergeEnvelope,
  type BranchMergeRecord,
  type UndoMergeEnvelope,
  type BranchListEnvelope,
  type BranchPreview,
  type CreateBranchBody,
  type MergeChange,
  type MergeChangeDetail,
  type MergeEntityKind,
  type MergeFieldChange,
  type MergeTreeDiff,
  type MergeSchemaField,
  type BranchMergeRequest,
  type BranchReviewComment,
  type BranchReviewState,
  type CreateMergeRequestBody,
  type CreateReviewCommentBody,
  type DeclineMergeRequestBody,
  type MergeRequestStatus,
  type ReviewRenderSide,
  type ReviewUserLabel,
  type MergeDirection,
  type MergePlan,
  type MergeResolution,
  type RenameBranchBody,
  type SiteBranch,
} from './schemas'
